spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: plxhyfrlnemyhd
    password: 278c0b79239bd7170025d9e8389c641765789662702cca6aa246c6e96ffc0cde
    url: jdbc:postgresql://ec2-44-198-82-71.compute-1.amazonaws.com:5432/d89incaj6mj3tm
  sql:
    init:
      plataform: postgres
  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl: true