spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: xojyfspnlmjjqc
    password: 87124d084921ad01c160c3e2a3ab2108164b7a0ec913e09e0427ae20087ad083
    url: jdbc:postgresql://ec2-54-159-22-90.compute-1.amazonaws.com:5432/d8ldm7d1b0tjq

  sql:
    init:
      plataform: postgres
  jpa:
    hibernate:
      ddl-auto: none
      generate-ddl: true